export enum tCompetitionStatusType {
  CREATION_PHASE = "CREATION_PHASE",
  REGISTRATION_PHASE = "REGISTRATION_PHASE",
  COMPETITION_PLANNING_PHASE = "COMPETITION_PLANNING_PHASE",
  PRE_COMPETITION_PHASE = "PRE_COMPETITION_PHASE",
  RUNNING_COMPETITION_PHASE = "RUNNING_COMPETITION_PHASE",
  CLOSED_COMPETITION_PHASE = "CLOSED_COMPETITION_PHASE",
}
