version: '2'
services:
  mysql:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: beerpongtournamentplaner
      MYSQL_USER: user
      MYSQL_PASSWORD: password