package de.guthe.sven.beerpong.tournamentplaner.datatype.authorization;

public enum SecurityPrivilege {

	WRITE_TEAM_PRIVILEGE, READ_TEAM_PRIVILEGE, ADMIN_TEAM_PRIVILEGE, WRITE_COMPETITION_PRIVILEGE, READ_COMPETITION_PRIVILEGE, ADMIN_COMPETITION_PRIVILEGE, WRITE_ACL_PRIVILEGE, READ_ACL_PRIVILEGE, ADMIN_ACL_PRIVILEGE, WRITE_AUTHENTICATION_PRIVILEGE, READ_AUTHENTICATION_PRIVILEGE, ADMIN_AUTHENTICATION_PRIVILEGE

}
